### PR TITLE
remove all graph node in loop

### PR DESCRIPTION
**Pull request by lizhiyuanUSTC**
Hi,
  I changed your code, and all variables are created before the graph started. Evaluating and testing will be faster.

### CODE REVIEW

**Comment by lizhiyuanUSTC** [comment]
Soory, I am not familar with git...

**Comment by crisb-DUT** [comment]
Hi @lizhiyuanUSTC ,

It's pretty cool! I will review it when there is a gap time.

Thanks

**Comment by crisb-DUT** [comment]
Hi @lizhiyuanUSTC ,

Thank you very much for your great contributions. And it would be better if you pull the master branch codes firstly and merge them into your own branch before pulling your request. Anyway, your works are pretty cool!

Thanks.

**Comment by lizhiyuanUSTC** [comment]
Okay， I will try it again.

**Comment by crisb-DUT** [comment]
Hi @lizhiyuanUSTC ,

Actually, I have already merged your pull request, so you don't have to that this time.

Best regards,
Wenbo

**Pull request merged**
